//console.log('hello')
//const personName = prompt('please enter your name?')
//alert(`Welcome to Flatburger, ${personName}`)
//const num1 = Number(prompt('enter your 1 st number'))
//console.log(num1)
//console.log(typeof num1)
//const num2 = Number(prompt('enter your second number'))
//console.log(num2)
//console.log(typeof num2)
//alert(`The sum is ${num1+num2}`)
//console.log(7 === 7)
//console.log(7 !== 7)
//console.log(7 == '7')
let greetingphrase = isstudent === true ? `hello ${personname}, welcome!`: "Goodbye"
